"""Backend factory + protocol.

Two implementations live in `backend_mock` and `backend_real`. Choose
via env var `CADDY_BACKEND=mock|real` (default: real inside the container,
mock in dev).
"""

import os
from typing import Protocol, Optional

from models import Route, GlobalSettings, CertInfo, ReloadResult


class Backend(Protocol):
    def list_routes(self) -> list[Route]: ...
    def get_route(self, route_id: str) -> Optional[Route]: ...
    def upsert_route(self, route: Route) -> None: ...
    def delete_route(self, route_id: str) -> None: ...

    def get_global(self) -> GlobalSettings: ...
    def update_global(self, g: GlobalSettings) -> None: ...

    def list_certs(self) -> list[CertInfo]: ...

    def render_caddyfile(self) -> str: ...
    def validate(self) -> ReloadResult: ...
    def reload(self) -> ReloadResult: ...
    def tail_logs(self, n: int = 200) -> list[str]: ...

    def is_managed(self) -> bool: ...
    def has_imported(self) -> bool: ...
    def import_existing(self) -> int: ...
    def reset(self) -> None: ...

    def check_upstream(self, upstream: str) -> dict: ...
    def check_subdomain(self, subdomain: str, route_id: str = "") -> dict: ...


def get_backend() -> Backend:
    mode = os.environ.get("CADDY_BACKEND", "real").lower()
    if mode == "mock":
        from backend_mock import MockBackend
        return MockBackend()
    from backend_real import RealBackend
    return RealBackend()


def backend_mode() -> str:
    return os.environ.get("CADDY_BACKEND", "real").lower()
