[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:azurite]
command=azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --location /data --loose --skipApiVersionCheck
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:storage-explorer]
command=dotnet /opt/azure-storage-explorer/AzureStorageExplorer.dll
autostart=true
autorestart=true
environment=ASPNETCORE_URLS="http://+:8080",AZURITE="true",AZURE_STORAGE_CONNECTIONSTRING="%(ENV_AZURE_STORAGE_CONNECTIONSTRING)s"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
