name: Build azurite-azure-storage

on:
  push:
    branches: [main]
    paths:
      - "containers/azurite-azure-storage/**"
  pull_request:
    paths:
      - "containers/azurite-azure-storage/**"

jobs:
  build:
    uses: ./.github/workflows/build-container.yml
    with:
      container_name: azurite-azure-storage
    permissions:
      contents: read
      packages: write
